mutex:
	gcc -o mutex.out mutex.c
	./mutex.out

spinlock:
	gcc -o spinlock.out spinlock.c
	./spinlock.out

producer-consumer:
	gcc -o producer-consumer.out producer-consumer.c
	./producer-consumer.out

race_condition:
	gcc -o race_condition.out race_condition.c
	./race_condition.out

clean:
	rm *.out
